# Generated by Django 4.2.6 on 2023-11-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_emp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=30)),
                ('publicationyear', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='emp',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
