# Generated by Django 4.2.6 on 2023-12-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_book_alter_emp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=20)),
            ],
        ),
    ]
